[package]
name = "uuid7time"
version = "1.0.0"
edition = "2021"

[dependencies]
uuid = { version = "1.8", features = ["v7"] }
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
